<?php
function gsappfacebook_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {	
	if ($op == 'insert' || $op == 'update') {
		$fbuid  = fbconnect_get_fbuid();
   	if (user_is_logged_in() && $fbuid) {
    	$message = t('Check out my latest post on !site...', array('!site' => variable_get('site_name', t('YOUR SITE'))));

      $_SESSION['fbconnect_gsappfacebook'] = array();
      $_SESSION['fbconnect_gsappfacebook']['message'] = $message;
      $_SESSION['fbconnect_gsappfacebook']['name'] = $node->title;
			$_SESSION['fbconnect_gsappfacebook']['link'] = url(drupal_get_path_alias('node/' . $node->nid), array('absolute' => TRUE));
			$_SESSION['fbconnect_gsappfacebook']['description'] = $node->field_excerpt[0]['value'];
			$_SESSION['fbconnect_gsappfacebook']['picture'] = url(($node->field_images[0]['filepath']), array('absolute' => TRUE));
			
    }
		$_SESSION['post_to_fb'] = $node->facebook['post'];
	if(in_array('alumni',$node->taxonomy['tags'])) { 
      $_SESSION['post_to_fb'] = 1;
    }	
  }
}

function gsappfacebook_preprocess_page(&$vars) {
  global $user;
	$fbuid  = fbconnect_get_fbuid();
	if (user_is_logged_in() && $fbuid && $_SESSION['post_to_fb'] != null) {
		if (!empty($_SESSION['fbconnect_gsappfacebook'])) {
     	drupal_add_js(
       	"function publish() {
					FB.ui(
						{
					  	method: 'stream.publish',
							name: \"" . $_SESSION['fbconnect_gsappfacebook']['name'] . "\",
							link: '" . $_SESSION['fbconnect_gsappfacebook']['link'] . "',
							picture: '" . $_SESSION['fbconnect_gsappfacebook']['picture'] . "',
							message: \"" . $_SESSION['fbconnect_gsappfacebook']['description'] . "\",	
							to: 112971615402197,
							from: 112971615402197,
							actions: [
								{ name: 'Read More', link: '" . $_SESSION['fbconnect_gsappfacebook']['link'] . "' }
							]
					  },
					  function(response) {
					    if (response && response.post_id) {
					      alert('Post was published.');
					    } else {
					      alert('Post was not published.');
					    }
					  }
					);
				}", 'inline'
       );
			drupal_add_js('window.onload = publish;', 'inline');
      $vars['scripts'] = drupal_get_js();
      unset($_SESSION['fbconnect_gsappfacebook']);
		}
	}
	unset($_SESSION['post_to_fb']);
}

/**
 * Implementation of hook_form_alter().
 */
function gsappfacebook_form_alter(&$form, $form_state, $form_id) {
		
	if($form_id == 'notes_node_form' || $form_id == 'briefs_node_form' || $form_id == 'papers_node_form') {
	  $form['facebook'] = array(
	     '#type' => 'fieldset',
	     '#title' => t('Post to facebook.com'),
	     '#collapsible' => TRUE,
	     '#collapsed' => FALSE,
	     '#tree' => TRUE,
	   );

	   $form['facebook']['post'] = array(
	     '#type' => 'checkbox',
	     '#title' => t('Announce this post on Facebook'),
	     '#default_value' => (empty($form['nid']['#value'])),
	     '#id' => 'facebook-toggle',
	   );
	}
			
}